#!/usr/bin/env ruby
# frozen_string_literal: true
# Builds the base image for running containerized CI on DigitalOcean.

require "securerandom"

IMAGES = %w[
  pakyow/ci-ruby-2.5.7
  pakyow/ci-ruby-2.6.5
  pakyow/ci-ruby-head
].freeze

require "dotenv"
Dotenv.load(".env.local", ".env")
$LOAD_PATH.unshift File.expand_path(".", "lib")

require "sshkey"
ssh_key = SSHKey.generate

require "pakyow/ci/remote/system"
Pakyow::CI::Remote::System.ephemeral(name: "pakyow-ci-#{SecureRandom.hex(4)}", ssh_public_key: ssh_key.ssh_public_key) do |server|
  server.shell keys: [ssh_key.private_key] do |shell|
    # Install unzip.
    #
    shell.run "apt-get -y install unzip"

    # Install Docker.
    #
    shell.run "curl -fsSL https://get.docker.com -o get-docker.sh"
    shell.run "sh get-docker.sh"
    shell.run "rm get-docker.sh"

    # Install Docker Compose.
    #
    shell.run "curl -L \"https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"
    shell.run "chmod +x /usr/local/bin/docker-compose"

    # Cache the images.
    #
    IMAGES.each do |image|
      shell.run "docker pull #{image}"
    end

    shell.run "poweroff"
  rescue IOError
    # we get this when the machine powers off
  end

  puts "waiting 300s for the server to power off..."
  sleep 300; server.image!(name: "pakyow-ci-#{Time.now.to_i}", family: "pakyow-ci")
end
